### ISSUE TITLE
PID files not in sync with the logrotate ones

### ISSUE THREAD

**Issue by afortiorama** [HEP-Puppet/arc_ce#32]
Hi,

the default names of the grid-manager and gridftp pid files in  the puppet configuration are different from those used in the logrotate files distributed in the rpm. This causes logrotate to malfunction because it cannot find the pid to send the signal too. For the grid-manager the name of the file cannot even be changed.

Logrotate

[root@vm3 ~]# grep pid /etc/logrotate.d/nordugrid-arc-*
/etc/logrotate.d/nordugrid-arc-arex:	kill -HUP `cat /var/run/arched-arex.pid 2> /dev/null` 2> /dev/null || true
/etc/logrotate.d/nordugrid-arc-gridftpd:	kill -HUP `cat /var/run/gridftpd.pid 2> /dev/null` 2> /dev/null || true

Puppet

aforti@vm57>grep pidfile ~/github/arc_ce/templates/*
/home/aforti/github/arc_ce/templates/gridftpd.erb:pidfile="<%= @run_directory %>/gridftpd.pid"
/home/aforti/github/arc_ce/templates/grid-manager.erb:pidfile="<%= @run_directory %>/grid-manager.pid"

IMO the default should be the same as logrotate or puppet should edit logrotate too.

**Comment by afortiorama** [comment]
I've committed the changes to parametrize the logrotate files.

https://github.com/afortiorama/arc_ce

**Comment by rwf14f** [comment]
ARC5 is EOL.
