### ISSUE TITLE
apply_fixes

### ISSUE THREAD

**Issue by afortiorama** [HEP-Puppet/arc_ce#34]
Hi,

since I've produced my set of fixes and have given them a version I've also changed the way apply_fixes works. instead of a booleian I've converted it to empty string by default or fix version. So to apply 4.0.0 apply_fixes => '4.0.0' to apply 5.4.1 apply_fixes => '5.4.1'

Only problem existing right now is if the files from one patch to the other differ so for glue-generator.pl I've added a link.

**Comment by rwf14f** [comment]
ARC5 is EOL.
